pki:
  base-url: http://ip:port
  # 认证地址
  auth-url: ${pki.base-url}/MessageService
  # 应用标识
  app-id: appid
  # 调用应用服务器或网关生成原文
  random-from: 1
  # 是否检查访问控制状态
  access-control: false
  # 是否开启开维码认证
  qr-code-auth: false
  # 生成二维码地址
  generate-qr-code-url: ${pki.base-url}/jit_qrcode_generate
  # 查询二维码状态地址
  query-qr-code-state-url: ${pki.base-url}/jit_qrcode_poll?Service_Type=qrcode_poll&jit_qrcode=